Blog.AdminCMS/Models/Blog/BlogIndexModel.cs
using Arthas.Blogs.Infrastructure.Tool.Web.Paging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Blog.AdminCMS.Models.Blog
{
    public class BlogIndexModel : IndexModelBase
    {
        public PagedList<BlogListModel> PagedList { get; set; }

        public int CategoryId { get; set; }
    }
}

Blog.AdminCMS/Models/Blog/BlogListModel.cs
using Arthas.Blogs.Core.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Blog.AdminCMS.Models
{
    public class BlogListModel
    {
        public int ID { get; set; }

        public string Title { get; set; }

        public string Category { get; set; }

        public BlogStatus Status { get; set; }

        public int ApproveCount { get; set; }

        public DateTime LastUpdate { get; set; }

        public int RepliesCount { get; set; }
    }
}

Blog.AdminCMS/Models/Blog/BlogModel.cs
using Arthas.Blogs.Core.Model;
using System.ComponentModel.DataAnnotations;

namespace Blog.AdminCMS.Models
{
    public class CreateBlogModel : ModelBase
    {
        public CreateBlogModel()
        {
            Status = BlogStatus.Normal;
        }

        [Required]
        public string Title { get; set; }

        public string Description { get; set; }

        public string Content { get; set; }

        public int CategoryID { get; set; }

        [Required]
        public string Tags { get; set; }

        public BlogStatus Status { get; set; }

        public int StatusValue { get; set; }
    }

    public class EditBlogModel : CreateBlogModel
    {
        public int ID { get; set; }
    }
}

Blog.AdminCMS/Controllers/AjaxQueryController.cs
using Arthas.Blogs.Infrastructure.Tool.FileStorages;
using Arthas.Blogs.Core;
using Arthas.Blogs.Core.Commands;
using Arthas.Blogs.Core.Queries;
using Arthas.Blogs.Core.Queries.Specifications;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace Blog.AdminCMS.Controllers
{
    public class AjaxQueryController : ControllerBase
    {
        readonly IFileStorage FileStorage;
        readonly IDataQuerier DataQuerier;
        private string FileContainer = "Assets";
        private string FilePath = "Image/";

        public AjaxQueryController(IFileStorage fileStorage,IDataQuerier dataQuerier,IWebshopBus Bus)
        {
            WebshopBus = Bus;
            DataQuerier = dataQuerier;
            FileStorage = fileStorage;
        }

        public JsonResult GetImageList(int pageSize = 10, int pageIndex = 0)
        {
            var query = DataQuerier.GetQuery(PhotoSpec.IsUsefulness(Arthas.Blogs.Core.Model.ImageStatus.ForEditor));
            int totalCount = query.Count();
            var result = query.OrderBy(it => it.ID).Skip(pageSize * pageIndex).Take(pageSize).Select(item => new 
            {
                Path = item.PhotoPath,
                Name = item.PhotoName
            });

            return Json(new { totalCount = totalCount, data = result }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetBlogReplies(int blogID, int pageSize = 10, int pageIndex = 0)
        {
            var toReply = DataQuerier.GetOne(BlogSpec.IsNotDelete().And(BlogSpec.HasBlogID(blogID)));
            int totalCount = toReply.Reviews.Where(it => it.IsDeleted == false).Count();
            var query = toReply.Reviews.Where(it =>it.IsDeleted == false).OrderByDescending(it => it.CreateDateTime).Skip(pageSize * pageIndex).Take(pageSize).Select(item => 
                new 
                {
                    CreateDate = item.CreateDateTime,
                    Content = item.Content,
                    ReviewerName = item.Reviewer.UserName,
                    ReviewerEmail = item.Reviewer.Email
                }).ToList();
            return Json(new { data = query , totalCount = totalCount },JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Upload()
        {
            try
            {
                var file = Request.Files[0];

                var Uri = FileStorage.Save(file.InputStream, FileContainer, FilePath + Path.GetFileNameWithoutExtension(file.FileName) + Guid.NewGuid() + Path.GetExtension(file.FileName));

                var publicUri = HttpContext.Request.Url.AbsoluteUri
                    .Replace(HttpContext.Request.Url.LocalPath, "")
                    .Replace(":" + HttpContext.Request.Url.Port, "") 
                    + Uri.ToString();

                WebshopBus.Send(new CreatePhotoCommand(
                    Path.GetFileNameWithoutExtension(file.FileName),
                    publicUri, 
                    Arthas.Blogs.Core.Model.ImageStatus.ForEditor));
                //Iframe based uploads(IE and Opera) require a Content-type of text/plain or text/html for the JSON response.
                //they will show an undesired download dialog if the iframe response is set to application/json.
                var headerAcceptVariable = this.Request.Headers["ACCEPT"] as string;

                if (headerAcceptVariable != null && headerAcceptVariable.Contains("application/json"))
                {
                    return Json(new { 
                        Succ = true,
                        Name = file.FileName,
                        Path = publicUri
                    });
                }
                else
                {
                    JavaScriptSerializer serializer = new JavaScriptSerializer();
                    var response = serializer.Serialize(new {
                        Succ = true,
                        Name = file.FileName,
                        Path = publicUri
                    });

                    return Content(response);
                }
            }
            catch (Exception ex)
            {
                return Json(new { Succ = false, Message = ex.Message });
            }
        }

    }
}

Blog.AdminCMS/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;

using Arthas.Blogs.Core;
using Arthas.Blogs.Core.Queries;
using Arthas.Blogs.Core.Queries.Specifications;
using Arthas.Blogs.Core.Model;
using Arthas.Blogs.Core.Commands;
using Blog.AdminCMS.Models;
using Blog.AdminCMS.Models.Blog;
using Arthas.Blogs.Infrastructure.Tool.Exceptions;
using Arthas.Blogs.Infrastructure.Tool.Web.Paging;
using Arthas.Blogs.Infrastructure.Tool.Helper;

namespace Blog.AdminCMS.Controllers
{
    public class BlogController : ControllerBase
    {
        #region Ctor
        readonly IDataQuerier DataQuerier;

        public BlogController(IWebshopBus Bus,IDataQuerier dataQuerier)
        {
            WebshopBus = Bus;
            DataQuerier = dataQuerier;
        }
        #endregion

        #region Index
        public ActionResult Index(BlogIndexModel indexModel)
        {
            var spec = BlogSpec.IsNotDelete();
            if (string.IsNullOrEmpty(indexModel.Keyword) == false)
            {
                spec = spec.And(BlogSpec.HasKeyword(indexModel.Keyword));
            }
            if (indexModel.CategoryId != 0)
            {
                spec = spec.And(BlogSpec.IsCategory(indexModel.CategoryId));
            }

            var query = DataQuerier.GetQuery(spec);

            indexModel.PagedList = query.OrderByDescending(it => it.CreateDate).Select(it =>
                new BlogListModel()
                {
                    ID = it.ID,
                    Title = it.Title,
                    Category = it.Category.CategoryName,
                    Status = it.Status,
                    ApproveCount = it.ApprovalCount,
                    LastUpdate = it.LastUpdate,
                    RepliesCount = it.ReadCount
                })
                .ToPageList(indexModel.PageIndex, indexModel.PageSize);

            return View(indexModel);
        }
        #endregion

        #region Create
        public ActionResult Create()
        {
            ViewBag.CategoryJson = JsonDotNetHelper.ConvertToJson(DataQuerier.GetQuery(
                CategorySpec.IsNotDelete<Category>())
                .Select(item =>
                    new 
                    {
                        ID = item.ID,
                        Name = item.CategoryName
                    })
            );
            ViewBag.BlogStatus = JsonDotNetHelper.EnumConvertToJson(typeof(BlogStatus));
            return View(new CreateBlogModel());
        }

        [HttpPost, ValidateAntiForgeryToken, ValidateInput(false)]
        public ActionResult Create(CreateBlogModel viewModel)
        {
            try
            {
                var status = (BlogStatus)viewModel.StatusValue;
                WebshopBus.Send(new CreateBlogCommand(viewModel.Title, viewModel.Description, viewModel.Content, viewModel.CategoryID, viewModel.Tags, status));
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                viewModel.ErrorMessages.Add(ex.Message);
                return View(viewModel);
            }
        }
        #endregion

        #region Edit
        public ActionResult Edit(int id)
        {
            var domianModel = DataQuerier.GetByID<Arthas.Blogs.Core.Model.Blog,int>(id);
            var viewModel = Mapper.Map<Arthas.Blogs.Core.Model.Blog, EditBlogModel>(domianModel);

            ViewBag.CategoryJson = JsonDotNetHelper.ConvertToJson(DataQuerier.GetQuery(
             CategorySpec.IsNotDelete<Category>())
             .Select(item =>
                 new
                 {
                     ID = item.ID,
                     Name = item.CategoryName
                 })
            );
            ViewBag.BlogStatus = JsonDotNetHelper.EnumConvertToJson(typeof(BlogStatus));

            return View(viewModel);
        }

        [HttpPost, ValidateAntiForgeryToken, ValidateInput(false)]
        public ActionResult Edit(EditBlogModel viewModel)
        {
            try
            {
                var status = (BlogStatus)viewModel.StatusValue;
                WebshopBus.Send(new EditBlogCommand(viewModel.ID, viewModel.Title, viewModel.Description, viewModel.Content, viewModel.CategoryID, viewModel.Tags, status));
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                viewModel.ErrorMessages.Add(ex.Message);
                return View(viewModel);
            }
        }
        #endregion

        #region Delete
        [HttpPost]
        public JsonResult Delete(int id)
        {
            try
            {
                WebshopBus.Send(new DeleteBlogCommand(id));
                return Json(new InfoMessage(true));
            }
            catch (Exception ex)
            {
                return Json(new InfoMessage(false, ex.Message, ex.StackTrace));
            }
        }
        #endregion 

        #region Ajax
        public JsonResult Query(string keyword = "", int catetoryid = 0, int pageIndex = 0, int pageSize = 10)
        {
            var spec = BlogSpec.IsNotDelete();
            if (string.IsNullOrEmpty(keyword) == false)
            {
                spec = spec.And(BlogSpec.HasKeyword(keyword));
            }
            if (catetoryid != 0)
            {
                spec = spec.And(BlogSpec.IsCategory(catetoryid));
            }

            var query = DataQuerier.GetQuery(spec);

            var totalCount = query.Count();
            var list = query.OrderByDescending(it => it.CreateDate).ThenByDescending(it => it.Status).Skip(pageIndex * pageSize).Take(pageSize).ToList();
            var result = list.Select(item => new
            {
                ID = item.ID,
                Title = item.Title,
                Category = item.Category.CategoryName,
                Status = Enum.GetName(typeof(BlogStatus),item.Status) ?? "",
                ApproveCount = item.ApprovalCount,
                LastUpdate = item.LastUpdate.ToString("yyyy-MM-dd HH:mm"),
                RepliesCount = item.Reviews == null ? 0 : item.Reviews.Where(rv => rv.IsDeleted == false).Count()
            });

            return Json(new { data = result , totalCount = totalCount },JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetReviews(int BlogID)
        {
            var blog = DataQuerier.GetByID<Arthas.Blogs.Core.Model.Blog, int>(BlogID);
            var reviews = blog.Reviews.Where(rv => rv.IsDeleted == false).Select(item => new 
            {
                Reviewer = item.Reviewer.UserName,
                ReviewerImage = item.Reviewer.ProfileImage,
                Content = item.Content
            });
            return Json(reviews, JsonRequestBehavior.AllowGet);
        }
        #endregion
    }
}

Blog.AdminCMS/Views/Blog/Create.cshtml
@model Blog.AdminCMS.Models.CreateBlogModel
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
@using (Html.BeginForm("Create", "Blog", FormMethod.Post))
{
    @Html.Partial("_BlogForm", Model)
}

Blog.AdminCMS/Views/Blog/Edit.cshtml
@model Blog.AdminCMS.Models.EditBlogModel
@{
    ViewBag.Title = "Edit";
}

<h2>@Model.Title</h2>
@using (Html.BeginForm("Edit", "Blog", FormMethod.Post))
{
    @Html.Partial("_BlogForm", Model)
}

Blog.AdminCMS/Views/Blog/Index.cshtml
@using Blog.AdminCMS.Models.Blog
@model BlogIndexModel
@{
    ViewBag.Title = "Index";
}

<h2>Blogs</h2>
<div id="BlogContainer">
    <div class="row row-margin">
        <div class="col-md-8">
            <a href="@Url.Action("Create")" class="btn btn-primary">Add Blog</a>
        </div>
        <div class="col-md-4">
            <div class="input-group">
                <input type="text" class="form-control" id="js-keyword">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="button" id="js-search">Search</button>
                </span>
            </div>
        </div>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover js-table">
            <thead>
                <tr>
                    <th class="sorting" aria-column="Title">Title</th>
                    <th class="sorting" aria-column="Category">Category</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.PagedList)
                {
                    <tr class="odd gradeX">
                        <td>
                            @Html.DisplayFor(it => item.Title)
                        </td>
                        <td>
                            @Html.DisplayFor(it => item.Category)
                        </td>
                        <td>
                            <a href="@Url.Action("Edit", new { id = item.ID })" class="btn btn-info btn-xs">
                                <span class="glyphicon glyphicon-pencil"></span>
                                Edit
                            </a>
                            <a class="btn btn-xs btn-danger btn-removable js-delete" data-id="@item.ID" data-url="@Url.Action("Delete")">
                                <span class="glyphicon glyphicon-remove"></span>
                                Delete
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        @Html.Partial("_Pager", Model.PagedList)
    </div>
    <div class="modal fade" id="ReplyList" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Replies</h4>
                </div>
                <div class="modal-body">
                     <!-- ko foreach:Reviews -->
                    <div class="row row-margin">
                           
                            <div class="col-md-4">
                                <img class="img-rounded" width="100" data-bind="attr: { src: $data.ReviewerImage, alt: Reviewer }">
                            </div>
                            <div class="col-md-8">
                                <h4 ><small data-bind="    text: Reviewer"></small></h4>
                                <p data-bind="text: Content"></p>
                            </div>
                            
                            <span>&nbsp;</span>
                    </div>
                    <!-- /ko -->
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/html" id="reviewTemplate">
    <!-- ko if:$data['RepliesCount'] > 0 -->
    <a href='#ReplyList' data-toggle='modal' data-target='#ReplyList' data-bind="click: function () { $root.onCustomEvent('displayReview', $data) }">
        <span data-bind="text: $data[$column.field]"></span>&nbsp;个回复
    </a>
    <!-- /ko -->
    <!-- ko ifnot:$data['RepliesCount'] > 0 -->
    <span data-bind="text: $data[$column.field]"></span>&nbsp;个回复
    <!-- /ko -->
</script>
<script type="text/javascript">
    $(function () {
        var blogVM = function() {
            self.Reviews = ko.observableArray();

            self.DisplayReview = function(data) {
                $.get('@Url.Action("GetReviews")', { BlogID: data.ID }, function(result) {
                    self.Reviews(result);
                });
            };
        };
        var viewModel = new blogVM();
        ko.applyBindings(viewModel, $("#BlogContainer")[0]);
    });
</script>

Blog.AdminCMS/Views/Blog/_BlogForm.cshtml
@model Blog.AdminCMS.Models.CreateBlogModel
@{
    var categoryJson = ViewBag.CategoryJson;
    var blogStatusJson = ViewBag.BlogStatus;
}
@Scripts.Render("~/Scripts/tinymce/tinymce.min.js")
@Scripts.Render("~/Scripts/bootstrap-select.min.js")
@Scripts.Render("~/bundles/bootstrap-select")
@Scripts.Render("~/bundles/jqueryfileupload")
@Styles.Render("~/Content/bootstrap-select.min.css")
@Html.AntiForgeryToken()
<div id="formContainer">
    <div class="form-group">
        @Html.LabelFor(m => m.Title)
        @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Title)
    </div>
    <div class="form-group">
        <label>Category</label>
        <select class="selectpicker outline" data-style="btn-success" data-bind="selectPicker: categoryValue, selectPickerOptions: { options: categorys, optionsText: 'Name', optionsValue: 'ID' }"></select>
        <input type="hidden" name="CategoryID" id="CategoryID" data-bind="value: categoryValue" />
    </div>
    <div class="form-group">
        <label>Status</label>
        <select class="selectpicker outline" data-style="btn-success" data-bind="selectPicker: blogStatusValue, selectPickerOptions: { options: BlogStatus, optionsText: 'label', optionsValue: 'value' }"></select>
        <input type="hidden" name="StatusValue" id="StatusValue" data-bind="value: blogStatusValue" />
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Description)
        @Html.TextAreaFor(m => m.Description, new { @class = "form-control tinymce", @rows = 5 })
    </div>
    <div class="form-group">
        <a class="btn btn-success" data-toggle="modal" data-target="#ImageList">Uploaded Images</a>

        <div class="modal fade" id="ImageList" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title" id="myModalLabel">Uploaded Images</h4>
                    </div>
                    <div class="modal-body">
                        <div class="row-margin">
                            <a class="upload btn btn-primary" href="#">Add
                                <span class="inputfile">
                                     <input type="file" id="select-image" name="pdfFile" accept=".jpg,.png">
                                </span>
                            </a>
                        </div>
                        <div id="result-grid"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Content)
        @Html.TextAreaFor(m => m.Content, new { @class = "form-control tinymce" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Tags)
        @Html.TextBoxFor(m => m.Tags, new { @class = "form-control", @placeholder = "splite with ','" })
    </div>
    <div>
        <button class="btn btn-primary" type="submit" data-loading-text="正在加载...">Submit</button>
        <a class="btn btn-default" href="@Url.Action("Index")">Cancle</a>
    </div>
    
</div>
<script type="text/javascript">
    $(function () {
        var formVM = function () {
            var self = this;

            self.categorys = ko.observableArray(@Html.Raw(categoryJson));
            self.categoryValue = ko.observable(@Model.CategoryID);

            self.BlogStatus = ko.observableArray(@Html.Raw(blogStatusJson));
            self.blogStatusValue = ko.observable(@((int)Model.Status));

            self.ImageList = ko.observableArray([]);
            self.totalCount = ko.observable();
            self.pageSize = ko.observable(10);
            self.pageIndex = ko.observable(0);
            self.renderImageList = function () {
                $.get('@Url.Action("GetImageList", "AjaxQuery")', { pageSize: self.pageSize(), pageIndex: self.pageIndex() }, function (result) {
                    self.totalCount(result.totalCount);
                    self.ImageList(result.data);
                })
            }
        }

        var viewModel = new formVM();
        ko.applyBindings(viewModel, $("formContainer")[0]);

        $('#formContainer').fileupload({
            dataType: 'json',
            method: "Post",
            url: "@Url.Action("Upload", "AjaxQuery")",
            done: function (e, data) {
                if (data.result.Succ == true) {
                    viewModel.ImageList.push({Path : data.result.Path,Name:data.result.Name});
                } else {
                    alert(data.result.Message);
                }
            },
            add: function (e, data) {
                var file = data.files[0];
                if (true) {
                    data.submit();
                } else {
                    RET.AdminCMS.Dialog.Message("");
                }
            }
        });

        $("#result-grid").dataGrid({
            data: viewModel.ImageList,
            columns: [
                {
                    headerText: "Preview",
                    field:"Path",
                    template: "<img data-bind='attr:{src:$data[$column.field]}' height='60'/>"
                },
                {
                    headerText: "Name",
                    field: "Name"
                },
                {
                    tdClass: "photo path",
                    headerText: "Path",
                    field: "Path"
                }
            ],
            pagingOptions: {
                totalCount: viewModel.totalCount,
                pageSize: viewModel.pageSize(),
                currentPageIndex: viewModel.pageIndex,
                pageIndexRange: 10,
                onPaging: function (index, pageSize) {
                    viewModel.pageSize(pageSize);
                    viewModel.renderImageList();
                }
            }
        });

        tinymce.init({
            selector: 'textarea.tinymce',
            plugins: ["code", "preview", "link", "paste", "image"],
            height: 500,
            file_browser_callback: function (field_name, url, type, win) {
                if (type == 'image') {
                    $('#imageUpload').click();
                }
            }
        });
    });
</script>